### ISSUE TITLE
Remove unnecessary files at the end

### ISSUE THREAD

**Issue by akshaya-a** [allenai/python-package-template#80]
### 🐛 Describe the bug

If you use this template on windows (or a platform where the unlink command doesn't keep the file open in the current process) removal of personalize.py before doing any work breaks the program. I worked around this by manually removing personalize.py instead of letting it unlink itself

### Versions

python 3.9, latest template

**Comment by epwalsh** [comment]
7 months later.... 🤦 Sorry I missed this! Should be fixed by #112
